modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="sleepless"
version="1.0.0"
displayName="The Sleepless"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="nolybutt"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.sleepless]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.sleepless]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration